Refactor of STP architecture (#1234)
* Removal of FirstArrivalToBallInvariant.cpp and connect files/references. Equals to BallClosestToUs

* Short document at top of each invariant

* Short description at top of Invariants

* Short description at top of Tactics
New Structure of STP directories

* lowercased directories
Copied structure to headers aswell

* Corrected CMakeList with new directory structure (and organized the entries)

* Made new namespace and CMake-set for computations.
Placed determineMidfielderPosition() in new PositionComputations.cpp

* Added addition to PositionComputations.cpp with determineOpenPosition to replace the current determineMidfieldPosition

* Added evaluation of current plays and roles

* Added Goal- & PassComputations.
WIP moving functions from old plays to there.

* Merge development into FilteringSTP (#1202)

* Added ControlModule class and created its first functions/variables

* I think this makes the CMake cleaner

* Started recreating functions based on the ones in Skill.cpp

* Started moving functionality to ControlModule

* Removed unused includes and fixed some static issues

* Couple more static issues

* Took out unnecessary method and moved variable definitions

* Took out unnecessary method and moved variable definitions

* Remove demorobot usage

* Fix typo from proto

* Fix roboteam_proto includes

* Piss off CodeFactor

* Changed static initialisation

* Updated error message and header documentation

* Renamed formations and started saving commands in vector

* Revert "Renamed formations and started saving commands in vector"

This reverts commit 398dcedf6aa75d2718f572c46045f7e00cd42db4.

* Save commands in vector, setup for new publishing and some debugging lines

* Attempt fixing IOmanager

* fix ai

* Fix rotation

* Check for double commands, start of new publish function

* CodeFactor stuff

* Invalid robotID check and attempt at publisher

* CodeFactor

* Fix central server connection

* Fix blocking problem

* Fix requested changes

* Fix codefactor

* Cleanup cmake and move features to roboteam_suite

* Fix proto problems

* Fix codefactor

Co-authored-by: rolf <rolfvdhulst@gmail.com>
Co-authored-by: Yuhanun Citgez <y.citgez@student.utwente.nl>

* Made 3 position systems that return a score

ERROR:
fatal error: roboteam_proto/State.pb.h: No such file or directory
    7 | #include <roboteam_proto/State.pb.h>

* Expanded PositionComputations.cpp to consider factors: Openfieldness, Line of sight and Visibility of goal

* Finished function from previous commit

* Re-added OnInitialize so AI can run

* Normlized Scoring for Flag and Distance in Dealer. Previous: adding a flag would always be worse (no normalization on amount of flags added). Flags and distance have the same weight.

Added the option to make minimal distance a prior per role (CLOSE_TO_POSITION)

* Start of shrinking GetBallInDirection + temp remove of referee Plays

* Not working. The Dealer should always select the closest to the ball.

Idea was to add a priority to a Role, and normlized the Weights of the flags.

* Not working. The Solver has to have the priorities of a role, not the matrix.

Hack fix is to have closest to ball like keeper.

* Disabled more plays for easier testing

* HackyHacky. To fix the issue of the closest robot to ball, hackyhacky as been done where the role is comparable to Keeper.

* Added walling mechanics (new function determineWallPositions in PositionComputations.cpp

* Bug fix and added TODO's

* Made the wallers have the same PID as the keeper

* Adjusted BlockBall to be more generic

* Took getting ball out of GetBallInDirection, is now GetBehindBallInDirection

* Changed new tactic name in CMakeList

* Changed Invariants to global Evaluations and be combined with Scores

* WIP

* Dealer seems to work, but here are crashes. WIP

* WIP

* Rolls get distrubted on Role Priority. However, the score calcutations seem to not work correctly. Based on the distance to the desired position the robots should be chosen, but when rechoosing a play robots deside to switch roles whilst their position should be the best for their previous role.

* Preivous mentioned bug occurs when there are multiple roles classes (defender+midfielder) that have the same priority.

* Start of passing the StpInfos to where scores will be calculated, using these StpInfos

* Removed/replaced redundant includes

* Moved intersectCircle function to utils/Circle

* Uncommented play initialisations again. Also removed KEEPER priority for now, this should be in the Dealer PR

* Shortened includes and moved a global constant to the local function

* Improved passComputations functions

* Removed unnecessary namespaces

* Improve getLongestSegment in goalComps, John's suggestion

Co-authored-by: Yuhanun Citgez <y.citgez@student.utwente.nl>

* Removed draw calls and changed shadowed variable

* Changed pairs to ScoreResult struct + some documentation

* Fix getLongestSegment with max_element

* Issue commit with supposedly an singleton bug in World.

Created a new module for PlayScores (to be change to PlayEvaluator) to save information in between plays and reduce repeating computations.
Created a method of calculating the score based on uint_8 scores and weights.

* Merge conflict

* Cleaned PositionComputations::determineWallPositions

* Bug fix determineWallPositions

* Bug fix determineWallPositions v2

* small adjustment CMakeList

* Pairs changed to PositionEvaluation struct

* Extra explanation for Dealer

* syntax for comments

* - Fix out-of-bounds write to an array by replacing it with a map

* Rename of PlayScorer to PlayEvaluator.

Implemented Invariants (also Start and Keep) into the module aswell as the score calculation (needs to be tested)

* Refactoring out all Invariants to Evaluations (big oef).
Score implementation printed in display

* Shows score in ai windows, tab ' Plays'

* Replacing pair in scoring of a play with a PlayScorer struct

* Renaming function to make more sense
Introducing structures to replace std::pairs

* Start to future/past StpInfos

* Replaced last Pairs with Structs.

* Split up the distribute function

* Changed pointers for PlayEvaluator to Ref

* Fixed outdated commit from Jaro (applicationmanager)
std::map to unordered for globalEvaluation map

* Missed a &

* Use of Iterators and split up priority and its order

* Small adjustments

* Function for saving necessary information between 2 Plays

* Fixes for PR

* Refining PositionComputations.cpp.

Saving computed positions every tick

* made namespace for generalized structs, grids and profiles

* Virtual function for getting all Roles whose information needs to be saved. For now save this Role's stpInfo, but there will be a new struct for this

* Rebuild position score computations

* more comments

* new field functions that places a point inside the field

* cleanup walling

* fix flickering

* added TimeToPositionEvaluation.cpp that compares 2 robots to get to a point

* small name change

* todo rewording

* more references

* Variable lastPlay to store the lastPlay in, but most likely doesnt work. Also struct PlayInfo to store the information in

* previousPlayInfo is now saved in new play

* working on dealer forcedID

* changed to reference

* Tested and works

* Comments from Yuhanun

* Comments from Yuhanun

* Comments from Yuhanun and failsave for invalid ID's

* correct @parm to @memberof for structs

* Merge debugging

* Creation of PlayTemplate and moving stuff to gen namespace

* small fixes

* Play AggressiveStopFormation.cpp

Added blockingposition

* small adjustment

* TimeOut Play refactored to new STP architecture (#1218)

* Halt Play refactored to new STP architecture & fixed segfault bug for getWallPosition() when ball is outside of field

* Second attempt at fixing getWallPosition segfault, and make keeper shoot at our closest robot if it has the ball instead of their goal

* Refactored DefensiveStopFormation and changed Formation Roles to BallAvoider in some referee Plays

* Refactored BallPlacementThem Play to new STP layout

* Refactored BallPlacementUs Play to new STP layout

* Refactored KickOffUs Play to new STP layout

* Refactored KickOffThem Play to new STP layout

* Refactored KickOffThemPrepare Play to new STP layout

* Refactored KickOffUsPrepare Play to new STP layout

* Refactored PenaltyThem Play to new STP layout

* Refactored PenaltyThemPrepare Play to new STP layout

* Refactored PenaltyUsPrepare Play to new STP layout

* Refactored DefendPass and fixed a bug in BlockBall where the blocking robot would stand behind instead of in front of the enemy robot

* Refactored Attack and removed shouldRoleSkipEndTactic from DefendPass

* Refactored evaluation, roles and flagmap of GenericPass

* Revert "Refactored evaluation, roles and flagmap of GenericPass"

This reverts commit 5e0623411e0c13e1afd0d8db7903b373aadfe918.

* Refactored GetBallRisky Play to new STP layout (#1224)

* Refactored ReflectKick Play to new STP layout (#1225)

* Fixed the calculations from GenericPass. But the play itself (passer role) is still not working

* Change PenaltyUs (#1223)

Refactor the PenaltyUs to confirm the PlayTemplate

Co-authored-by: JaroKuiken <50826688+JaroKuiken@users.noreply.github.com>

* Changed priorities

* Attacking pass refactor (#1228)

* Refactored ReflectKick Play to new STP layout

* Begin of reintegration AttackingPass

* Attempt to reintegrate pass and receive calculations

* Reduced cpu intensity by removing double calculations, fixed grid locations and make sure we always pass somewhere

* Removed Halt's for more useful roles

* Final tweaks to AttackingPass

* keepPlayEvaluation improvement

* Use more logical evaluations for GetBallPossession

* Attacking pass refactor (#1229)

* Refactored ReflectKick Play to new STP layout

* Begin of reintegration AttackingPass

* Attempt to reintegrate pass and receive calculations

* Reduced cpu intensity by removing double calculations, fixed grid locations and make sure we always pass somewhere

* Removed Halt's for more useful roles

* Final tweaks to AttackingPass

* keepPlayEvaluation improvement

* Let Keeper shoot to one of our nearby robots

* Uncommented GenericPass play

* Uncommented GenericPass play

* Refactor FreeKickThem to conform with PlayTemplate. (#1230)

Co-authored-by: JaroKuiken <50826688+JaroKuiken@users.noreply.github.com>

* Defend shot refactor (#1233)

* Start of refactor DefendShot

* Changed some Defenders to Wallers and fixed segfault

* Comment out TestPlay

* Resolving of comments for the PR into Development

* Removing of the copying of world. Probably not working, functions still need to be checked

* Removed the copying of world in PositionComputations.cpp

* Keeper no longer chosen as closest robot in dealer

* Fixed SIGSEV for Attack and AttackingPass, improved pass power

* Remove limitAngularVel for now, as it makes the robot spin too fast with the ball

* Fix multiple codefactor blank line warnings

* Update src/stp/plays/PlayTemplate.cpp

Co-authored-by: Yuhanun Citgez <yuhanun.c@gmail.com>

* Update src/stp/Play.cpp

Co-authored-by: Yuhanun Citgez <yuhanun.c@gmail.com>

* Fix Yuhanun's STP PR review comments

* Shortened includes

Co-authored-by: maxl <m.m.lievense@roboteamtwente.nl>
Co-authored-by: rolf <rolfvdhulst@gmail.com>
Co-authored-by: Yuhanun Citgez <y.citgez@student.utwente.nl>
Co-authored-by: Dawid Kulikowski <d.kulikowski@me.com>
Co-authored-by: mmlievenseRTT <77438742+mmlievenseRTT@users.noreply.github.com>
Co-authored-by: Floris-Hoek <p+github@fhoek.com>
Co-authored-by: Floris-Hoek <70347286+Floris-Hoek@users.noreply.github.com>
Co-authored-by: Martin Miksik <mamiksik@gmail.com>
Co-authored-by: j.a.kuiken@student.utwente.nl <05SwC4cgVrI7kT9tavp1>
Co-authored-by: Yuhanun Citgez <yuhanun.c@gmail.com>